In [7]:
import numpy as np
import pandas as pd


In [8]:
arr=np.array([10,20,30,40,50,60,70,80])
print("Array:",arr)
print("Array maen:",arr.mean())

Array: [10 20 30 40 50 60 70 80]
Array maen: 45.0


In [9]:
print(arr.reshape(2,4))
print()
print(arr[1:5])

[[10 20 30 40]
 [50 60 70 80]]

[20 30 40 50]


In [10]:
data={
    "Name":["AJ","BJ","CJ","DJ","EG"],
    "Marks":[98,89,99,85,86],
    "Age":[19,20,21,18,19],
    "Branch":["CSE","ECE","CSE","ISE","ME"]
}
df=pd.DataFrame(data)
print(df)


  Name  Marks  Age Branch
0   AJ     98   19    CSE
1   BJ     89   20    ECE
2   CJ     99   21    CSE
3   DJ     85   18    ISE
4   EG     86   19     ME


In [11]:
print("\n slicing: \n",df.iloc[0:3])
print("Marks: \n",df['Marks'])


 slicing: 
   Name  Marks  Age Branch
0   AJ     98   19    CSE
1   BJ     89   20    ECE
2   CJ     99   21    CSE
Marks: 
 0    98
1    89
2    99
3    85
4    86
Name: Marks, dtype: int64


In [12]:
print("Marks > 90 : \n",df[df["Marks"]>90])

Marks > 90 : 
   Name  Marks  Age Branch
0   AJ     98   19    CSE
2   CJ     99   21    CSE
